"""empty message

Revision ID: 0340b4c8d266
Revises: 6e9629bc8aa3
Create Date: 2023-03-07 21:14:42.463281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0340b4c8d266'
down_revision = '6e9629bc8aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('upcoming_shows',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('upcoming_shows',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('upcoming_shows',
               existing_type=sa.String(),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('upcoming_shows',
               existing_type=sa.String(),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)

    # ### end Alembic commands ###
