"""empty message

Revision ID: 60cbeb1371b0
Revises: 4a426d96d05e
Create Date: 2023-02-26 21:00:22.553933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60cbeb1371b0'
down_revision = '4a426d96d05e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('seking_venue', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('seeking_description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('past_shows', sa.ARRAY(sa.Integer()), nullable=True))
        batch_op.add_column(sa.Column('past_shows_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('upcoming_shows', sa.ARRAY(sa.Integer()), nullable=True))
        batch_op.add_column(sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('seking_talent', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('seeking_description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('past_shows', sa.ARRAY(sa.Integer()), nullable=True))
        batch_op.add_column(sa.Column('past_shows_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('upcoming_shows', sa.ARRAY(sa.Integer()), nullable=True))
        batch_op.add_column(sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('upcoming_shows_count')
        batch_op.drop_column('upcoming_shows')
        batch_op.drop_column('past_shows_count')
        batch_op.drop_column('past_shows')
        batch_op.drop_column('seeking_description')
        batch_op.drop_column('seking_talent')
        batch_op.drop_column('website')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('upcoming_shows_count')
        batch_op.drop_column('upcoming_shows')
        batch_op.drop_column('past_shows_count')
        batch_op.drop_column('past_shows')
        batch_op.drop_column('seeking_description')
        batch_op.drop_column('seking_venue')
        batch_op.drop_column('website')

    # ### end Alembic commands ###
