"""empty message

Revision ID: 86c46ffe0d30
Revises: d597c2fc96f5
Create Date: 2023-02-28 17:40:11.691784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c46ffe0d30'
down_revision = 'd597c2fc96f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('genres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.VARCHAR(length=500), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
