"""empty message

Revision ID: a2b68375b4c3
Revises: 6f61c2763f46
Create Date: 2023-03-10 20:10:12.072708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b68375b4c3'
down_revision = '6f61c2763f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('past_shows')
        batch_op.drop_column('past_shows_count')
        batch_op.drop_column('upcoming_shows')
        batch_op.drop_column('upcoming_shows_count')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('past_shows')
        batch_op.drop_column('past_shows_count')
        batch_op.drop_column('upcoming_shows')
        batch_op.drop_column('upcoming_shows_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('upcoming_shows', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('past_shows', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('upcoming_shows', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('past_shows', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
