"""empty message

Revision ID: cc1fecc7aede
Revises: 564cd74f54ee
Create Date: 2023-03-08 22:14:40.238474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1fecc7aede'
down_revision = '564cd74f54ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_constraint('shows_artist_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('shows_venue_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Artist', ['artist_id'], ['id'], ondelete='cascade')
        batch_op.create_foreign_key(None, 'Venue', ['venue_id'], ['id'], ondelete='cascade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('shows_venue_id_fkey', 'Venue', ['venue_id'], ['id'])
        batch_op.create_foreign_key('shows_artist_id_fkey', 'Artist', ['artist_id'], ['id'])

    # ### end Alembic commands ###
