"""empty message

Revision ID: e069f3b32a03
Revises: b864ce893114
Create Date: 2023-02-27 21:59:55.826091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e069f3b32a03'
down_revision = 'b864ce893114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_venue', sa.Boolean(), nullable=False))
        batch_op.drop_column('seking_venue')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_talent', sa.Boolean(), nullable=False))
        batch_op.drop_column('seking_talent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('seeking_talent')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seking_venue', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('seeking_venue')

    # ### end Alembic commands ###
