"""empty message

Revision ID: e2e87855cbe0
Revises: cc1fecc7aede
Create Date: 2023-03-08 22:43:50.323356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e87855cbe0'
down_revision = 'cc1fecc7aede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_constraint('shows_venue_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('shows_artist_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Venue', ['venue_id'], ['id'])
        batch_op.create_foreign_key(None, 'Artist', ['artist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('shows_artist_id_fkey', 'Artist', ['artist_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('shows_venue_id_fkey', 'Venue', ['venue_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
